#!/bin/sh

. /Applications/mampstack-7.1.18-1/scripts/setenv.sh

exec /Applications/mampstack-7.1.18-1/php/sbin/.php-fpm.bin -y /Applications/mampstack-7.1.18-1/php/etc/php-fpm.conf -p /Applications/mampstack-7.1.18-1/php/var/ -c /Applications/mampstack-7.1.18-1/php/etc/php.ini "$@"
