#!/bin/sh

. /Applications/mampstack-7.1.18-1/scripts/setenv.sh
SASL_PATH="/Applications/mampstack-7.1.18-1/common/lib/sasl2"
                export SASL_PATH
exec /Applications/mampstack-7.1.18-1/common/sbin/.saslpasswd2.bin -f "/Applications/mampstack-7.1.18-1/common/etc/sasldb2" "$@"
